export const CULTURE_REPOSITORY = Symbol('CULTURE_REPOSITORY');
export const CULTURE_CONTENT_REPOSITORY = Symbol('CULTURE_CONTENT_REPOSITORY');
export const CULTURE_ARTICLES_REPOSITORY = Symbol(
  'CULTURE_ARTICLES_REPOSITORY',
);
