export const CULTURE_REPOSITORY = Symbol('CULTURE_REPOSITORY');
export const CULTURE_EVENTS_REPOSITORY = Symbol('CULTURE_EVENTS_REPOSITORY');
export const CULTURE_ARTICLES_REPOSITORY = Symbol(
  'CULTURE_ARTICLES_REPOSITORY',
);

export const CULTURE_SUBSCRIPTIONS_REPOSITORY = Symbol(
  'CULTURE_SUBSCRIPTIONS_REPOSITORY',
);
