export const ApplicationConstants = {
  DATABASE_URL: 'DATABASE_URL',
  SUPERTOKENS_CORE_CONNECTION_URI: 'SUPERTOKENS_CORE_CONNECTION_URI',
  APP_NAME: 'APP_NAME',
  API_DOMAIN: 'API_DOMAIN',
  WEBSITE_DOMAIN: 'WEBSITE_DOMAIN',
  SUPERTOKENS_API_KEY: 'SUPERTOKENS_API_KEY',
};
