export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const USER_FOLLOWING_REPOSITORY = Symbol('USER_FOLLOWING_REPOSITORY');
export const USER_MESSAGE_REPOSITORY = Symbol('USER_MESSAGE_REPOSITORY');
export const USER_CHAT_REPOSITORY = Symbol('USER_CHAT_REPOSITORY');
